soundbridge/views/main.py
# soundbridge/views/main.py
import os
import requests
import google.auth.transport.requests

from flask import Blueprint, jsonify, redirect, request, url_for, session, render_template
from ..clients.spotify_client import get_user_playlists, get_playlist_tracks, get_playlist_name_by_id
from ..clients.youtube_client import get_youtube_playlist_tracks, get_youtube_playlists, get_youtube_playlist_name
from ..extensions import oauth
from authlib.integrations.base_client.errors import OAuthError
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import Flow

main = Blueprint('main', __name__)

os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "1" # dont use in prod

# index/main page
@main.route('/')
def index():
    user_connected_to_spotify = False
    user_connected_to_youtube = False
    spotify_token = session.get('token')
    youtube_credentials = session.get('youtube_credentials')
    request = google.auth.transport.requests.Request()

    if spotify_token and is_spotify_token_valid(spotify_token['access_token']):
        user_connected_to_spotify = True
    else:
        session.pop('token', None)
    
    youtube_credentials = session.get('youtube_credentials')
    if youtube_credentials:
        credentials = Credentials(**youtube_credentials)
        if credentials.expired and credentials.refresh_token:
            credentials.refresh(request)
            session['youtube_credentials'] = credentials_to_dict(credentials)
            user_connected_to_youtube = True
        elif not credentials.expired:
            user_connected_to_youtube = True

    return render_template('login.html', 
                           user_connected_to_spotify=user_connected_to_spotify,
                           user_connected_to_youtube=user_connected_to_youtube)

# auth route to spotify
@main.route('/spotify_login')
def spotify_login():
    redirect_uri = url_for('main.spotify_authorize', _external=True)
    print("Redirect URI:", redirect_uri)
    return oauth.spotify.authorize_redirect(redirect_uri)

# auth spotify w/ callback
@main.route('/spotify_login/authorize')
def spotify_authorize():
    try:
        token = oauth.spotify.authorize_access_token()
        session['token'] = token
        return redirect(url_for('main.index'))
    except OAuthError as error:
        print("OAuthError occurred: ", error)
        return render_template('login.html', error=error.description)

# get spotify playlists
@main.route('/spotify_playlists', methods=['GET'])
def show_spotify_playlists():
    token = session.get('token')
    
    if not token:
        return redirect(url_for('main.spotify_login'))

    playlists = get_user_playlists(token['access_token'])
    total_playlists = playlists['items']

    return render_template('spotify_playlists.html', 
                           playlists=total_playlists)

# get spotify playlist details
@main.route('/spotify_playlists/<playlist_id>')
def show_spotify_playlist_tracks(playlist_id):
    token = session.get('token')
    if not token:
        return redirect(url_for('main.login'))
    
    tracks = get_playlist_tracks(token['access_token'], playlist_id)
    playlist_name = get_playlist_name_by_id(token['access_token'], playlist_id)
    print("Playlist Name:", playlist_name)
    return render_template('spotify_playlist_tracks.html', 
                           tracks=tracks, 
                           playlist_name=playlist_name)

# spotify token check
def is_spotify_token_valid(token):
    response = requests.get(
        'https://api.spotify.com/v1/me', 
        headers={'Authorization': f'Bearer {token}'}
    )
    return response.status_code == 200

@main.route('/youtube_login')
def youtube_login():
    client_id = os.getenv("YOUTUBE_CLIENT_ID")
    client_secret = os.getenv('YOUTUBE_CLIENT_SECRET')
    redirect_uri = os.getenv('YOUTUBE_REDIRECT_URI')

    flow = Flow.from_client_secrets_file(
        'client_secrets.json',
        scopes=['https://www.googleapis.com/auth/youtube'],
        redirect_uri=redirect_uri
    )

    authorization_url, state = flow.authorization_url(
        access_type='offline',
        include_granted_scopes='true'
    )

    session['state'] = state

    return redirect(authorization_url)

@main.route('/youtube_login/authorize')
def youtube_authorize():

    state = session['state']
    redirect_uri=os.getenv('YOUTUBE_REDIRECT_URI')

    flow = Flow.from_client_secrets_file(
        'client_secrets.json',
        scopes=['https://www.googleapis.com/auth/youtube'],
        state=state,
        redirect_uri=redirect_uri
    )

    flow.fetch_token(authorization_response=request.url)

    youtube_credentials = flow.credentials

    if not youtube_credentials.valid:
        return 'Invalid credentials', 401

    youtube_credentials_dict = {
        'token': youtube_credentials.token,
        'refresh_token': youtube_credentials.refresh_token,
        'token_uri': youtube_credentials.token_uri,
        'client_id': youtube_credentials.client_id,
        'client_secret': youtube_credentials.client_secret,
        'scopes': youtube_credentials.scopes
    }

    session['youtube_credentials'] = youtube_credentials_dict
    print("Redirect URI:", redirect_uri)

    return redirect(url_for('main.index'))

@main.route('/youtube_playlists')
def show_youtube_playlists():

    youtube_credentials = session.get('youtube_credentials')

    if not youtube_credentials:
        return redirect(url_for('main.youtube_authorize'))

    playlists = get_youtube_playlists(youtube_credentials)

    return render_template('youtube_playlists.html', playlists=playlists)

@main.route('/youtube_playlists/<playlist_id>')
def show_youtube_playlist_tracks(playlist_id):
    youtube_credentials = session.get('youtube_credentials')

    if not youtube_credentials:
        return redirect(url_for('main.youtube_login'))

    tracks = get_youtube_playlist_tracks(youtube_credentials, playlist_id)
    playlist_name = get_youtube_playlist_name(youtube_credentials, playlist_id)

    return render_template('youtube_playlist_tracks.html', 
                           tracks=tracks, 
                           playlist_name=playlist_name)

def credentials_to_dict(credentials):
    return {
        'token': credentials.token,
        'refresh_token': credentials.refresh_token,
        'token_uri': credentials.token_uri,
        'client_id': credentials.client_id,
        'client_secret': credentials.client_secret,
        'scopes': credentials.scopes
    }
    
# playlist transfer page
@main.route('/playlist_transfers')
def playlist_transfers():
    user_connected_to_spotify = False
    user_connected_to_youtube = False
    spotify_token = session.get('token')
    youtube_credentials = session.get('youtube_credentials')
    request = google.auth.transport.requests.Request()

    if spotify_token and is_spotify_token_valid(spotify_token['access_token']):
        user_connected_to_spotify = True
    else:
        session.pop('token', None)
    
    youtube_credentials = session.get('youtube_credentials')
    if youtube_credentials:
        credentials = Credentials(**youtube_credentials)
        if credentials.expired and credentials.refresh_token:
            credentials.refresh(request)
            session['youtube_credentials'] = credentials_to_dict(credentials)
            user_connected_to_youtube = True
        elif not credentials.expired:
            user_connected_to_youtube = True

    return render_template('playlist_transfers.html', 
                           user_connected_to_spotify=user_connected_to_spotify,
                           user_connected_to_youtube=user_connected_to_youtube)

@main.route('/api/get-playlists/<service_name>')
def get_playlists(service_name):
    youtube_credentials = session.get('youtube_credentials')
    spotifyToken = session.get('token')

    if not youtube_credentials:
        return redirect(url_for('main.youtube_authorize'))
    
    if not spotifyToken:
        return redirect(url_for('main.spotify_login'))

    playlist_names = []

    if service_name == 'spotify':
        playlists = get_user_playlists(spotifyToken['access_token'])
        playlist_names = [playlist['name'] for playlist in playlists['items']]
        print(playlist_names)
    elif service_name == 'youtube':
        playlists = get_youtube_playlists(youtube_credentials)
        playlist_names = [playlist['title'] for playlist in playlists]
        print(playlist_names)
    else:
        return jsonify({"error": "Invalid service name"}), 400

    return jsonify({"playlists": playlist_names})

soundbridge/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}::soundbridge::{% endblock %}</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Syne+Mono&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    </head>
    <body>
        <header>
            <nav>
                <div class="navbar">
                    <div style="display: flex;">
                        <a href="{{ url_for('main.index') }}"><img src="{{ url_for('static', filename='../static/assets/sb_logo.png') }}" alt="logo" class="logo-img"></a>
                        <p>tools & services</p>
                        <p>privacy policy</p>
                    </div>
                    <div class="login-connection-container" style="margin: 0px;">
                        <a href="{{ url_for('main.index') }}" class="login-button" style="padding: 6px;">
                            <span class="material-symbols-outlined" style="margin-right: 8px;">
                                cable
                            </span>
                            <span>your connections.</span> 
                        </a>
                    </div>
                </div>
            </nav>
        </header>
        <main>
            {% block content %}
            {% endblock %}
        </main>
        <footer>
        </footer>
    </body>
    {% block scripts %}
    <script src="{{ url_for('static', filename='js/playlist_transfers.js') }}"></script>
    {% endblock %}
</html>

soundbridge/templates/login.html
{% extends 'base.html' %}

{% block title %}login to soundbridge.{% endblock %}

{% block content %}
<!-- <div class="login-alert-container">
    <span>you're already connected to that service!</span>
</div> -->
<div class="login-container" style="width: 90%; margin: auto;">
    <div class="page-header"> 
        <div><span class="gradient-text" style="font-size: 2rem;">::soundbridge::</span></div>
        <p style="margin-top: 8px;">view, export & transfer your playlists from music service to music service. follow the steps below to get started.</p>
    </div>
    <div class="step-container">
        <div class="step-text-container">
            <div style="font-size: 1.5rem; text-shadow: 3px 3px black;">
                1. connect to your music services.
            </div>
            <br>
            <div style="font-size: 1.3rem; text-shadow: 2px 2px black;">
                currently, soundbridge offers services for spotify and youtube music, with additional services planned for integration in the near future.
            </div>
        </div>
        <div class="login-button-container">
            <div class="login-connection-container">
                <a href="{{ url_for('main.spotify_login') }}" class="login-button">
                    <img src="../static/assets/spotify_icon.png">
                    <span>login ⇒ spotify.</span> 
                </a>
                {% if user_connected_to_spotify %}
                    <span class="login-connection-connected">connected!</span>
                {% else %}
                    <span class="login-connection-not-connected">not connected.</span>
                {% endif %}
            </div>
            <div class="login-connection-container">
                <a href="{{ url_for('main.youtube_login') }}" class="login-button">
                    <img src="../static/assets/yt_icon.png">
                    <span>login ⇒ youtube.</span> 
                </a>
                {% if user_connected_to_youtube %}
                <span class="login-connection-connected">connected!</span>
                {% else %}
                <span class="login-connection-not-connected">not connected.</span>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="step-container">
        <div class="step-text-container">
            <div style="font-size: 1.5rem; text-shadow: 3px 3px black;">
                2. choose an option.
            </div>
            <br>
            <div style="font-size: 1.3rem; text-shadow: 2px 2px black;">
                view information on your playlists and tracks, export playlist data, and transfer your playlists from music service to music service.
            </div>
        </div>
        <div class="login-button-container">
            <div class="login-connection-container">
                <a href="{{ url_for('main.show_spotify_playlists') }}" class="login-button">
                    <span class="material-symbols-outlined" style="margin-right: 4px; margin-top: 4px;">
                        visibility
                    </span>
                    <span>view your playlists.</span> 
                </a>
            </div>
            <div class="login-connection-container">
                <a href="{{ url_for('main.playlist_transfers') }}" class="login-button">
                    <span class="material-symbols-outlined" style="margin-right: 4px; margin-top: 4px">
                        compare_arrows
                    </span>
                    <span>transfer your playlists.</span> 
                </a>
            </div>
            <div class="login-connection-container">
                <a href="{{ url_for('main.spotify_login') }}" class="login-button">
                    <span class="material-symbols-outlined" style="margin-right: 4px;">
                        export_notes
                    </span>
                    <span>export your playlists.</span> 
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

soundbridge/templates/playlist_transfers.html
{% extends 'base.html' %}

{% block title %}playlist transfers.{% endblock %}

{% block content %}
<div class="playlist-transfer-container">
    <div class="playlist-transfer-intro">
        <div class="page-header"> 
            <div><span class="gradient-text" style="font-size: 2rem;">::playlist transfers::</span></div>
            <p style="margin-top: 8px; font-size: 1.5rem;">transfer your playlists between your different music services. select which service you'd like to transfer from in the <span class="gradient-text">::from::</span> section, and then select the service you'd like to transfer to in the <span class="gradient-text">::to::</span> section.</p>
        </div>
    </div>
    <div class="playlist-transfer-display-container">
        <div class="playlist-transfer-selection-container from-container">
            <div class="playlist-transfer-list-header">
                <div><span class="gradient-text" style="font-size: 1.8rem;">::from::</span></div>
                <div onclick="toggleDropdown('from-container')" class="selected-value from-value">
                    <span>
                        select service to transfer from.
                    </span>
                    <span class="material-symbols-outlined" id="dropdownCaretFrom">
                        arrow_drop_down
                    </span>
                </div>
            </div>
            <div class="playlist-transfer-options-container">
                <div class="custom-options from-options">
                    <div class="option"
                        onclick="selectOption('from-container', 'spotify.', '../static/assets/spotify_icon.png')"
                    >
                        <img src="{{ url_for('static', filename='../static/assets/spotify_icon.png') }}" class="service-logo">
                        <span>spotify.</span>
                    </div>
                    <div class="option"
                        onclick="selectOption('from-container', 'youtube.', '../static/assets/yt_icon.png')"
                    >
                        <img src="{{ url_for('static', filename='../static/assets/yt_icon.png') }}" class="service-logo">
                        <span>youtube.</span>
                    </div>
                </div>
                <div id="playlistContainer"></div>
            </div>
        </div>
        <div style="display: flex; flex-direction: column;">
            <span class="material-symbols-outlined" style="transform: scale(2.5);">
                multiple_stop
            </span>
            <div class="login-connection-container" style="width: 220px; margin: 30px 15px 30px 15px;">
                <a href="{{ url_for('main.index') }}" class="login-button" style="padding: 6px;">
                    <span class="material-symbols-outlined" style="margin-right: 4px;">
                        sound_sampler
                    </span>
                    <span>begin transfer.</span> 
                </a>
            </div>
        </div>
        <div class="playlist-transfer-selection-container to-container">
            <div class="playlist-transfer-list-header">
                <div><span class="gradient-text" style="font-size: 1.8rem;">::to::</span></div>
                <div onclick="toggleDropdown('to-container')" class="selected-value to-value">
                    <span>
                        select service to transfer to.
                    </span>
                    <span class="material-symbols-outlined" id="dropdownCaretTo">
                        arrow_drop_down
                    </span>
                </div>
            </div>
            <div class="playlist-transfer-options-container">
                <div class="custom-options to-options">
                    <div class="option"
                        onclick="selectOption('to-container', 'spotify.', '../static/assets/spotify_icon.png')"
                    >
                        <img src="{{ url_for('static', filename='../static/assets/spotify_icon.png') }}" class="service-logo">
                        <span>spotify.</span>
                    </div>
                    <div class="option"
                        onclick="selectOption('to-container', 'youtube.', '../static/assets/yt_icon.png')"
                    >
                        <img src="{{ url_for('static', filename='../static/assets/yt_icon.png') }}" class="service-logo">
                        <span>youtube.</span>
                    </div>
                </div>
                <div id="playlistContainer"></div>
            </div> 
        </div>
    </div>
</div>
{% endblock %}

soundbridge/templates/spotify_playlist_tracks.html
{% extends 'base.html' %}

{% block title %}soundbridge: {{ playlist_name }}{% endblock %}

{% block content %}
<div class="track-table-container">
    <div class="track-page-header-container">
        <img src="{{ url_for('static', filename='../static/assets/spotify_logo_white.png') }}" class="track-page-logo">
        <div class="track-intro">
            <div class="gradient-text" style="font-size: 2rem;">::{{ playlist_name }}::</div>
            <p style="font-size: 1.5rem;"> 
                see every track on this playlist in the table below.
            </p>
        </div>
    </div>
    <table class="playlist-table">
        <thead>
            <tr>
                <th>track name.</th>
                <th>artist.</th>
                <th>duration.</th>
                <!-- <th>Times Listened</th>
                <th>Total Hours</th>
                <th>Genre</th> -->
            </tr>
        </thead>
        <tbody>
            {% for item in tracks['items'] %}
                <tr>
                    <td>{{ item['track']['name'] }}</td>
                    <td>
                        {% for artist in item['track']['artists'] %}
                            {{ artist['name'] }}{% if not loop.last %}, {% endif %}
                        {% endfor %}
                    </td>
                    <td>
                        {{ item['track']['duration_ms'] | format_duration }}
                    </td>
                    <!--
                    <td>Total Hours Placeholder</td>
                    <td>Genre Placeholder</td> -->
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>    
{% endblock %}

soundbridge/templates/spotify_playlists.html
{% extends 'base.html' %}

{% block title %}your playlists.{% endblock %}

{% block content %}
<div class="playlist-container">
    <div class="playlist-intro">
        <div class="page-header"> 
            <div><span class="gradient-text" style="font-size: 2rem;">::your playlists::</span></div>
            <p style="margin-top: 8px;">view information about your playlists. click on one of the music services in the tabs below below to see your playlists on that service. </p>
        </div>
    </div>
    <div class="playlist-display-container">
        <div class="playlist-list">
            <div class="playlist-tabs">
                <a class="tab-active"><img src="{{ url_for('static', filename='../static/assets/spotify_icon.png') }}" style="height: 30px; width: auto; margin: auto;"></a>
                <a class="tab" href="{{ url_for('main.show_youtube_playlists') }}"><img src="{{ url_for('static', filename='../static/assets/yt_icon.png') }}" style="height: 40px; width: auto; margin: auto;"></a>
            </div>
            <div class="playlist-list-header">
                <img src="{{ url_for('static', filename='../static/assets/spotify_logo_white.png') }}" style="width: auto; height: 50px; display: flex;">
            </div>
            <div class="playlist-item-container">
                <ul>
                    {% for playlist in playlists %}
                        <li class="playlist-item">
                            <a href="{{ url_for('main.show_spotify_playlist_tracks', playlist_id=playlist['id']) }}" class="playlist-link">
                                {{ playlist['name'] }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>  
</div>
{% endblock %}

soundbridge/templates/youtube_playlist_tracks.html
{% extends 'base.html' %}

{% block title %}soundbridge: {{ playlist_name }}{% endblock %}

{% block content %}
<div class="track-table-container">
    <div style="display: flex;" class="track-page-header-container">
        <img src="{{ url_for('static', filename='../static/assets/yt_logo.png') }}" style="width: auto; height: 45px; display: flex; flex-direction: row; align-items: center;">
        <div class="track-intro">
            <div class="gradient-text" style="font-size: 1.8rem;">::{{ playlist_name }}::</div>
            <p style="font-size: 1.3rem;"> 
                see every track on this playlist in the table below.
            </p>
        </div>
    </div>
    <table class="playlist-table">
        <thead>
            <tr>
                <th>track name.</th>
                <th>artist/uploader.</th>
                <th>duration.</th>
            </tr>
        </thead>
        <tbody>
            {% for item in tracks %}
                <tr>
                    <td>{{ item['title'] }}</td>
                    <td>{{ item['artist']}}</td>
                    <td>{{ item['duration'] | parse_duration }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>    
{% endblock %}

soundbridge/templates/youtube_playlists.html
{% extends 'base.html' %}

{% block title %}your playlists.{% endblock %}

{% block content %}
<div class="playlist-container">
    <div class="playlist-intro">
        <div class="page-header"> 
            <div><span class="gradient-text" style="font-size: 2rem;">::your playlists::</span></div>
            <p style="margin-top: 8px;">view information about your playlists. click on one of the music services in the tabs below below to see your playlists on that service. </p>
        </div>
    </div>
    <div class="playlist-display-container">
        <div class="playlist-list">
            <div class="playlist-tabs">
                <a class="tab" href="{{ url_for('main.show_spotify_playlists') }}"><img src="{{ url_for('static', filename='assets/spotify_icon.png') }}" style="height: 30px; width: auto; margin: auto;"></a>
                <a class="tab-active"><img src="{{ url_for('static', filename='assets/yt_icon.png') }}" style="height: 40px; width: auto; margin: auto;"></a>
            </div>
            <div class="playlist-list-header">
                <img src="{{ url_for('static', filename='assets/yt_logo.png') }}" style="width: auto; height: 40px; display: flex;">
            </div>
            <div class="playlist-item-container">
                <ul>
                    {% for playlist in playlists %}
                        <li class="playlist-item">
                            <a href="{{ url_for('main.show_youtube_playlist_tracks', playlist_id=playlist['id']) }}" class="playlist-link">
                                {{ playlist['title'] }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>  
</div>
{% endblock %}